baseURL = "https://chapter23.uk/"
languageCode = "en-uk"
title = "Chapter 23"
theme = "PaperMod"

[pagination]
pagerSize = 4

[params]
defaultTheme = "light"
disableThemeToggle = true
disableScrollToTop = true
hideFooter = true
mainSections = ["posts"]

[params.profileMode]
enabled = true
title = "Chapter 23"
subtitle = "an anon non prophet eristocratic dysorganisation"

[[params.profileMode.buttons]]
name = "get texts"
url = "/posts/"

[[menu.main]]
identifier = "posts"
name = "Mnemos"
url = "/posts/"
weight = 10
